# Generated by Django 4.2.4 on 2024-06-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='Code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='Prompt',
            new_name='prompt',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='Prompt_title',
            new_name='prompt_title',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='Summary',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='Wikipedia_link',
            new_name='wikipedia_link',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='updated_at',
        ),
    ]
