# Generated by Django 5.1.7 on 2025-03-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_alter_prompt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='Prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='Prompt_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
