# Generated by Django 4.2.4 on 2025-04-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_alter_prompt_prompt_alter_prompt_prompt_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wikipedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikipedia_url', models.URLField(blank=True, null=True)),
                ('mermaid_Code', models.TextField(blank=True, null=True)),
                ('p5_code', models.TextField(blank=True, null=True)),
                ('three_Code', models.TextField(blank=True, null=True)),
                ('d3_code', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
