# Generated by Django 5.1.7 on 2025-04-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_wikipedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='mcq',
            field=models.TextField(blank=True, null=True),
        ),
    ]
