# Generated by Django 5.1.7 on 2025-04-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0007_prompt_mcq'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipedia',
            name='code_avaliable',
            field=models.BooleanField(default=False),
        ),
    ]
