# Generated by Django 5.1.7 on 2025-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0008_wikipedia_code_avaliable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='Code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='mcq',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
