# Generated by Django 5.1.7 on 2025-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0010_wikipedia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipedia',
            name='mcq',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wikipedia',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
