# Generated by Django 5.1.7 on 2025-04-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0011_wikipedia_mcq_wikipedia_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipedia',
            name='remix1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wikipedia',
            name='remix2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wikipedia',
            name='remix3',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
