# Generated by Django 5.1.7 on 2025-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0012_wikipedia_remix1_wikipedia_remix2_wikipedia_remix3'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipedia',
            name='mcq_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
